### ISSUE TITLE
Get correct folks assigned to teams, assigned to the project.

### ISSUE THREAD

**Issue by jaredsinclair** [Underdog-Devs/website#24]
Make sure that:

1) Everyone who needs GitHub access has it.

2) Look into the optimal way to do this (teams/groups to have blanket permissions, not per-individual permissions, if possible).

**Comment by robertjallen** [comment]
I believe that would be to make everyone owners not members.

**Comment by jaredsinclair** [comment]
Current status:

- Need to gather more GitHub usernames of folks that should be here

- Access to UDD repos should **not** be done by adding individual contributors anymore.

- Access to UDD repos will be governed through GitHub "Teams". 

- To add a developer to the UDD repos, they will need to be invited by an UDD Owner to the [Developers team](https://github.com/orgs/Underdog-Devs/teams/developers).

This will be the sanest way to ensure that folks have the correct level of permissions across the organization, and makes it clearer who is and who is not a member of UDD.

**Comment by jaredsinclair** [comment]
@robertjallen This setup also obviates the need to hand out owner-level membership.
