### ISSUE TITLE
Wireframe / Website Layout

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#25]
## Summary

Create a mock up for each page of the Underdogs Website. This should be 100% illustrative, and have no functionality. This should provide a clear picture of the layout of each page. We will use this as the source of truth when building this website and all of our dev work will align to this. That said, this is not the end all be all. We can change the website design as we progress through the project but this will be our launching point so that we are all on the same page. Please keep the design simple, clean, and user friendly. 

Feel free to draw on a piece of paper or use an online tool.

## Acceptance Criteria

- Mock up of each page on the Underdog Devs website. Pages include:
        - Landing Page (Home Page): This will consist of an About Us, Mission Statement, Get Involved
        - Mentee Page: Headshots of each mentee, brief bio below the headshot
        - Mentor Page: Headshot of each mentor, brief bio below each headshot
- Must include Nav Bar
- Must include Footer
- Must include Underdog Devs logo

## Discussion

N/A

## Screenshots

N/A

## Additional Information

N/A

**Comment by JessBonanno** [comment]
I used figma and some templates to come up with a mockup for the landing page as well as a mentor/mentee page.  I think the mentee page can just be reused for the mentor page minus the "my work" section,  unless we want to keep that section in for mentors as well.  The mockups include logo, header, navbar, footer etc.  Let me know what you think.   Everything is totally open to edits and revisions, just what I came up with so far.  Mostly filled with lorem ipsum. Heres the link to view and or edit the mockup. 
https://www.figma.com/file/Pqh5K3G3VcjhDImekaMeWl/UDD-mockup?node-id=2%3A1871

**Comment by matthewweale** [comment]
Hi @JessBonanno. @CalJersey, @MisterC-Rogers - I wanted to check in to see how everything was coming along. I checked out the figma mock up @JessBonanno posted above and I really like the design so far very simple and easy to read. Is this the final design or are you still working through some things? Let me know so I can provide some feedback that I have. If you are all still in the idea generating phase, I want to continue to let you ideate before providing some of my insight.

**Comment by JessBonanno** [comment]
I'm not sure if anything is going to be added, I think feedback would be great at this point to help guide any changes or additions. @matthewweale. @CalJersey, @MisterC-Rogers what do you guys think?

**Comment by CalJersey** [comment]
I am lagging due to how busy I’ve been. I promise I will look at the work Jess has done on a laptop today as soon as I get a chance. Had no luck viewing on mobile. I will send any feedback I have soon. Matt, may as well as yours too at this point.

**Comment by matthewweale** [comment]
Right on. Here is some of my feedback:

1. Actual header names. For example, I see you have things like "Our Story", "Building a Network", or "Our Culture" and I am not sure if these are final names or just placeholders. If they are placeholders, could we finalize the names? If they are final, I would be curious to know what information is going in each one. I was thinking it could be useful to have things like: What is a mentor? Who is a mentee? About Us. Our Story (which you have already). I would not worry about finalizing the actual content in each one but it would be a good idea to know what type of content would be put in each heading.
2. What does the mentee / mentor page look like? This is not **your** personal page that you will design but rather the page that has a headshot and description of each mentee/mentor. Then I would click the headshot and it would take me to the page that specific mentee designed. There would be one mentee page and one mentor page like this. 
3. Help: I see you created a link to this in the Nav Bar but don't see a mock up.
4. Get Involved: I see you created a link to this in the Nav Bar but don't see a mock up. Unless it just takes you to the bottom part of the page?
5. Footer Links: There are a bunch of page links in the footer (become a mentee, become a mentor, request info, etc.). Can we make mock ups of these?

Overall this is a great start. Keep in mind, we are going to need a mock up for literally everything. It doesn't have to be completely finalized yet and can be a work in progress. But we are going to want a starting point for each page. So even if the design is not final, having a mock up will be helpful so we know we will have to make that page eventually. I think it would be safe to assume that if there is no page mock up we will not be designing it.

I hope the above is helpful and please let me know if I can clarify anything. Thanks again for all the hard work on this so far

**Comment by JessBonanno** [comment]
@matthewweale can you see the "Personal Page" in the mockup?  That is the mentor/mentee mockup first draft.  If you can't see it let me know and I'll try to figure out why.

**Comment by JessBonanno** [comment]
@MisterC-Rogers @CalJersey is there a time this coming week or weekend that you might be able to meet with me so we can go over the feedback from Matt?  I'm free weekdays 3pm to 7pm est generally, I have few appointments this week but I can work around them if you let me know your availability.  This coming weekend is mostly free as of now.

**Comment by matthewweale** [comment]
@JessBonanno - No I can see it, but to my understanding each mentee would have free range of how to design their page. I think what you have could be a good starting point for someone just getting started though.

I have no idea how to use figma and probably just made the worst mock up possible but hopefully it gets my idea across. Each big box would be a headshot of a mentee and the small box below would be a little bio about them. Then you would click the headshot and it would take you to their personal page, similar to the one you have already designed. Does that make sense?

**Comment by JessBonanno** [comment]
Ah ok, I get what you're saying.  A "view all" type of page.  I'll mock something up and report back with any decisions we come up with based on your feedback.  Thanks Matt!

**Comment by MisterC-Rogers** [comment]
@JessBonanno you would have to say time and date, I will be there I have been building this Shopify site and have not had a lot of time

**Comment by JessBonanno** [comment]
@MisterC-Rogers @CalJersey can you both be available Thursday at 5pm EST?

**Comment by CalJersey** [comment]
I can’t see the personal page for some reason.

I have some feedback about the landing page. The overall design feels a bit too sparse for me, too much whitespace. Perhaps we could add some kind of background or border pattern around the outside instead of all the white? Either that or add a background color behind every other set of content instead of the extended whitespace to delineate and liven it up a bit. Also, I think the header logo and text are too small in relation to other elements of the page. Up size them by 1.5 - 2X. Just my opinion. What do you guys think?

-Dan

**Comment by CalJersey** [comment]
No I will be at work unfortunately. I am on PST, so couldn’t do it until 8pm EST. Any chance that works for you guys?

**Comment by JessBonanno** [comment]
@CalJersey I have class from 7-10 every weekday except Friday.  Would Friday be better to meet?  I can also do pretty much any time Sunday with a heads up.  What about you @MisterC-Rogers?

**Comment by CalJersey** [comment]
Heh, we basically have exact opposite schedules. Usually I’m off on Fridays, but am working 6 days/week through the end of the year. So Saturday is my only day off. Can we continue to stay synced via email and Slack instead?

**Comment by JessBonanno** [comment]
Yea, we can make it work no worries, I think slack is best so we don't blow up email notifications.
