### ISSUE TITLE
Git Repo Folder Structure

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#26]
## Summary

Create an intuitive folder structure within the Git repository. This folder structure should align with the [Wireframe / Website Design](https://github.com/Underdog-Devs/website/issues/25) we have chosen. This folder structure should also align with the [frameworks](https://github.com/Underdog-Devs/website/issues/35) (Front and Back End) we have chosen to use to build the website with. 

## Acceptance Criteria

- Supports the backend and front end frameworks
- Components Folder with Sub Components Folder: Ex. footerComponent Folder, headerComponent Folder
- Pages Folder: This will house each page on the Underdog Devs website. Home Page, Mentee Page, Mentor Page, each individuals pages.
- CSS Folder
- SCSS Folder
- Pictures Folder

## Discussion

N/A

## Screenshots

N/A

## Additional Information

N/A

**Comment by matthewweale** [comment]
## Summary

*Very brief summary of the foreseen changes.*

## Acceptance Criteria

- Write a list here
- of all of the expectations
- that must be satisfied
- in order for the feature or change
- to be considered complete

## Discussion

*Add extended discussion here*

## Screenshots

*optional*

## Additional Information

*relevant links to Slack messages, for example*

**Comment by matthewweale** [comment]
Hi @juanresendiz813 - I wanted to check in to see how this ticket is coming along. Have you gotten a chance to start on it? If not, no worries. Please let me know if you have any blockers that are preventing from starting this so that we can work to remove them. If there are no blockers I would love to understand where some of your thoughts are so far so please post a comment on this ticket. Talk soon, Matt

**Comment by juanresendiz813** [comment]
Hey Matt! I've been looking up a lot of best practices and I see why I have to work with two more tickets on the board in order to get it structured properly. Jess just reached out to me recently so we're meeting tomorrow in order to get some lead way. Ill check with the other ticket participants as well to see how it is going. By Tuesday I should have something going in order for everyone to review this week. If I run into anything Ill be sure to reach out(which I'm sure I wil be soon lol). Either way Ill keep you posted. Thanks!

**Comment by matthewweale** [comment]
Thanks for the update @juanresendiz813! Glad to see you leveraging the other mentees, that is awesome teamwork and something that you will do on a daily basis in a full time role. Please let me know if there is anything I can do as well.

**Comment by juanresendiz813** [comment]
https://whimsical.com/join/AcPtPYGFP7Kn3YFPht6bp2?invite=rcl7koq2

Hey Matt, here is a link to the draft folder structure we are thinking about. We noticed it will most likely be written in React but if that changes we can just edit where needed. You can add and edit yourself with the attached link. Thanks.

**Comment by matthewweale** [comment]
@juanresendiz813 - Nice job man, this is perfect. I really don't have any feedback. Once we decide on a framework we may need to adjust slightly but I think the structure you picked out should be pretty adaptable. Nice work again!
