### ISSUE TITLE
Individual Dev Branches

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#27]
Each person working on this project must create their own development branch. This branch will be the only place this person works from, and will be used for all merge requests. **Please follow the below nomenclature for consistency:**

firstInitiallastName_dev 
As an example, my branch will be called: mweale_dev. m = firstInitial, weale = lastName. Everyone will have "_dev"

**Comment by robertjallen** [comment]
How do you feel about feature branches?  
Many big merge conflicts are results of long-living branches. If you work in your own branch for several days or even weeks, the risk is high that someone else changes parts of the code you have touched in another branch. That would lead to merge conflicts.

**Comment by robertjallen** [comment]
A feature branch could be nav-bar or footer. When the feature is done and after a pull request is merged it could be closed or deleted. Its a really good way to help avoid merge conflicts.

**Comment by matthewweale** [comment]
@robertjallen - I think that is a great idea. Here are a couple of my thoughts:

1. Personal Branches - These would be used for when you are developing your own webpage. In theory, nothing you do here should be connected to anyone else's work so we should not have to worry about merge conflicts.
2. Feature Branches - I am cool with using these, however communication is key here. Many parts of a website are dependent on others. So it is possible two feature branches have some overlap and that each developer is talking to the other to make sure we avoid those merge conflicts. I think this is doable, but something we will have to keep top of mind. Maybe we only work on very small features.

How does that sound?

**Comment by robertjallen** [comment]
Sounds perfect 👌

Feature branches for while developing a particular component or Feature.
(Communicate effectively)

Personal branches for adding content to a personal page.
