### ISSUE TITLE
Add a pull request template.

### ISSUE THREAD

**Issue by jaredsinclair** [Underdog-Devs/website#29]
<here's an example template>

## Purpose

*one sentence summary of the intent of your pull request*

## Related Issues

*links to related GitHub issues*

## Discussion

*extended discussion of your changes*

## How to Test

*instructions for how others can test your changes*

## Screenshots

*optional*

## Checklist

- [ ] What things
- [ ] Do we want each
- [ ] pull request to have
- [ ] in a manual checklist?

**Comment by jlong5795** [comment]
Just want to make sure it's known there is a template that is already part of the repo that will either need to be updated or removed if deemed insufficient.

**Comment by sygint** [comment]
Closed as we have an existing one that is working at the moment in https://github.com/Underdog-Devs/website/blob/main/pull_request_template.md
