### ISSUE TITLE
Determine Frameworks (Back-End & Front-End)

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#35]
Determine what web frame works we will work with. For example, Node, Express, React, Angular etc. What are the pros and cons of each?

**Comment by McLovinCSUN** [comment]
### **_React_**
**pros**
- VDOM-checks for changes in VDOM and then updates those sections only instead of updating the whole DOM
- The updates process is optimized and accelerated.
- popular in the industry  

**cons**
- it is hard to learn for beginners (true 😅)

**Comment by robertjallen** [comment]
React
CRA vs Next.js

Next.js apps are rendered on the client-side (CSR), but the framework supports server-side rendering (SSR), as well. By comparison, Create React App apps are rendered only on the client-side.

Both CRA and Next.js use React/ or VDOM.

**Comment by jlong5795** [comment]
### Front End Discussion

**React**
pros
- community support (various libraries/packages/tutorials/forums/blogs/etc)
- most of the team working on the project will likely be familiar with React

cons 
- might be heavier than we need. static, non-interactive sites don't need React.
- larger bundles take longer to access on moble

**Gatsby**
pros
- community support (various libraries/packages/tutorials/forums/blogs/etc)
- can be implemented along-side React component architecture
- supports injection of data via GraphQL queries to allow users to make their own updates
- provides context and structure for people to gain new skills

cons 
- will require some onboarding for team members who aren't familiar with it

**Typescript**
pros
- allows enforceable types for props, values, and objects
- provides context and structure for people to gain new skills

cons 
- will require some onboarding for team members who aren't familiar with it

**Comment by matthewweale** [comment]
Hi @jlong5795, @McLovinCSUN, @robertjallen, @dontbecypher16 - I wanted to check in to see how this was coming along. I see you all started to post your thoughts on the pros and cons of each framework. I think that is an awesome approach and will really help in making a clear decision that is based in fact. 
Have you guys finalized a framework or is this an ongoing discussion? Please let me know if there is anything I can do to help out. Talk soon, Matt

**Comment by jlong5795** [comment]
> Hi @jlong5795, @McLovinCSUN, @robertjallen, @dontbecypher16 - I wanted to check in to see how this was coming along. I see you all started to post your thoughts on the pros and cons of each framework. I think that is an awesome approach and will really help in making a clear decision that is based in fact.
> Have you guys finalized a framework or is this an ongoing discussion? Please let me know if there is anything I can do to help out. Talk soon, Matt

We took our conversation to Slack to be a bit more instant in communication. Perhaps we should summarize that conversation and add it to this ticket.

**Comment by matthewweale** [comment]
No worries, just wanted to check in here. Thanks for the update. Feel free to post a summary here and I can add my thoughts/feedback if you would like. Thanks for all the work on this so far, looking forward to seeing what you all come up with

**Comment by jlong5795** [comment]
A final decision requires a little bit of information about how the project will exist in the future. If this is going to be, at least in part, a project that is a landing web presence for the UD community and will allow its member to post profiles to highlight their work, something like Gatsby/React will be a good fit. If the static generation of Gatsby constrains the profiles more than intended a straight React application would be best. 

For backend, we aren't entirely sure if one is required at this stage. That is something that can be factored in as client side needs require it. Our general recommendation would be a Node/Express backend and PostgreSQL if database support is needed.
