### ISSUE TITLE
Jason Long: Make a brief list of web dev topics you would like to learn more about.

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#37]
## Summary

For Jason: Make a brief list of web dev topics you would like to learn more about.

## Acceptance Criteria

- In the comment thread attached to this issue, reply with a brief list of web dev topics that you would like to have more experience with.

- Chat with @matthewweale on Slack about the list so we can start making a plan to get you that experience you need.

## Discussion

Will discuss further on Slack.

**Comment by jlong5795** [comment]
I've been mulling this over for a couple weeks as this is an interesting question. There are two ways I see to approach an answer. There's technology specific questions, and there technology agnostic questions. I think that my biggest questions are more about process, career trajectory, and how to best grow as a developer. I passed a Java back end assessment after spending 2 days studying Java, I'm very confident in my ability to learn new languages and frameworks. My interest and where I get overwhelmed is what should I be doing? Is this a time to drill down on the concepts I've already learned, or to learn new skills. If so which ones, how do you go about making those decisions other than personal fancy? I think those are the kind of things I'd be most interested to talk about.
