### ISSUE TITLE
Jess Bonanno: Make a brief list of web dev topics you would like to learn more about.

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#38]
## Summary

For Jess: Make a brief list of web dev topics you would like to learn more about.

## Acceptance Criteria

- In the comment thread attached to this issue, reply with a brief list of web dev topics that you would like to have more experience with.

- Chat with @matthewweale on Slack about the list so we can start making a plan to get you that experience you need.

## Discussion

Will discuss further on Slack.

**Comment by JessBonanno** [comment]
- typescript
- graphQL

**Comment by JessBonanno** [comment]
- accessibility
