### ISSUE TITLE
Robert Allen: Make a brief list of web dev topics you would like to learn more about.

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#40]
## Summary

For Rob: Make a brief list of web dev topics you would like to learn more about.

## Acceptance Criteria

- In the comment thread attached to this issue, reply with a brief list of web dev topics that you would like to have more experience with.

- Chat with @matthewweale on Slack about the list so we can start making a plan to get you that experience you need.

## Discussion

Will discuss further on Slack.

**Comment by robertjallen** [comment]
The developer's burden is a never-ending to-do list of things to learn and/ or get more practice with. 

1. MySQL, PSQL
2. Do another full-stack front-to-back Next.js CRUD app
3. UX/UI
4. DS
5. Figma
6. Adobe tools
