### ISSUE TITLE
Maria Martinez: Make a brief list of web dev topics you would like to learn more about.

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#42]
## Summary

For Maria: Make a brief list of web dev topics you would like to learn more about.

## Acceptance Criteria

- In the comment thread attached to this issue, reply with a brief list of web dev topics that you would like to have more experience with.

- Chat with @matthewweale on Slack about the list so we can start making a plan to get you that experience you need.

## Discussion

Will discuss further on Slack.

**Comment by McLovinCSUN** [comment]
1. React- How to decided or layout components for the web app
2. React-How to properly use @media query (I think that's what it is called)
3. TypeScript-Any tutorials on TypeScript. I have not used language
4. chatboxes
5. progressive web applications
