### ISSUE TITLE
Create Footer Bar

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#50]
## Summary

Create the Footer bar based upon the agreed upon layout found [here](https://www.figma.com/file/Pqh5K3G3VcjhDImekaMeWl/UDD-mockup?node-id=2%3A1872). Please note, do not worry about styling the Nav bar to match the exact colors and buttons we have, rather make sure the layout matches

## Acceptance Criteria

- Create a branch called "footer_bar"
- Use Ant Design for the buttons
- In parts folder
- Code is well commented
- Code functions as intended with no bugs

**Comment by robertjallen** [comment]
![Screenshot 2020-12-23 093133](https://user-images.githubusercontent.com/20561145/103471800-893c0080-4d52-11eb-82e3-5ee5c05e153a.jpg)
