### ISSUE TITLE
Git Pre Commit Check

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#64]

**Comment by jlong5795** [comment]
Update:
The functionality I was thinking of was from a paid resource. However, I've done some research and I believe I can implement the same functionality without that resource. I'll be ready to test the solution 1/20

**Comment by sygint** [comment]
I think we could add some pre commit checks for jest (once we get testing in), prettier/eslint with husky and lint-staged

https://github.com/typicode/husky
https://github.com/okonet/lint-staged

**Comment by jlong5795** [comment]
> I think we could add some pre commit checks for jest (once we get testing in), prettier/eslint with husky and lint-staged
> 
> https://github.com/typicode/husky
> https://github.com/okonet/lint-staged

I agree. I can include these in this feature.

**Comment by sygint** [comment]
https://randyperez.tech/blog/husky-lint-staged

Here is a good write up for anyone interested in taking this on

**Comment by jlong5795** [comment]
I'm already assigned to this task.

**Comment by jlong5795** [comment]
Update: Refining the process to make it user friendly.
