### ISSUE TITLE
LandingPage - Want to get involved Component

### ISSUE THREAD

**Issue by matthewweale** [Underdog-Devs/website#70]
## Summary

Create the **Want to get involved?** Component to match the attached screenshot and design in [Figma](https://www.figma.com/file/Pqh5K3G3VcjhDImekaMeWl/UDD-mockup?node-id=2%3A1871). Feel free to use content/pictures of your choice.

## Acceptance Criteria

- Name the file getInvolved.js and put it in the LandingPage folder
- Put any pictures in the Assets folder
- Add this file to the landingPage.js file
- Pull the most recent main branch 
- Create a branch called get_involved to complete this work

## Screenshots

![Screen Shot 2021-01-16 at 3 07 03 PM](https://user-images.githubusercontent.com/50917450/104825090-a75f3180-5825-11eb-8340-b1860abf600d.png)

**Comment by jlong5795** [comment]
Closed. Referenced by issue #93
