### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by jlong5795** [Underdog-Devs/website#92]
## Summary
Refinement is needed in the navigation component of the site to prepare for live deployment.

## Acceptance Criteria
- Semantic markup tags used (ie: nav instead of div, etc)
- Component should be built in ./src/Components/NavBar.js
- Styling updates should be made in src/CSS/NavBar.module.css
- NavBar.js must be a functional component
- Code must compile and generate no new warnings
- Attach a screenshot of the completed work to this ticket as part of submission.

- Adjust spacing and alignment to match provided design
- Increase padding on "Get Involved" button to match design file
- Add scroll to #getInvolved as the onClick for the "Get Involved" button
- Refactor p tagged text into a tag links. They can point to "/#"

## Discussion

This is a collaborative project so please contact a project lead before updating or changing any project dependencies. NPM is the package manager of choice for this project.

Tickets are a living document. Please ask any questions, make any comments, any notes for future work on this ticket for discussion and record keeping purposes. 

## Screenshots

Design image
![image](https://user-images.githubusercontent.com/57104675/112012805-7df9a500-8af7-11eb-9654-10c5aab3e203.png)

## Additional Information

Expected completion date here:

**Comment by MisterC-Rogers** [comment]
how does the mobile nav look and what is the functionality of it? Does it slide in a side panel, dropdown a mini-menu, or something else?
what is the functionality of the get involved button? Does it open a modal with a form, or does it route to a new page view?

**Comment by jlong5795** [comment]
Right now the Get Involved button should push down the page to a component that is in development.

**Comment by jlong5795** [comment]
![image](https://user-images.githubusercontent.com/57104675/112772647-91c17180-8ff7-11eb-93f9-148edf7f5fae.png)
 Here is the mock up of the mobile version. This is the extent of the current design.
